Chore/migrating to matierial 5
BIBSYSDEV/InterLibraryLoan-react-frontend pull request #166
Opened 2022-04-19 16:01 UTC by anetteOlli

2022-04-20 08:00 UTC, pcb-unit requested changes

2022-04-20 10:59 UTC, anetteOlli commented on cypress/fixtures/example.json
> +{
ja, jeg kjørte prettier på hele prosjektet.

2022-04-20 10:59 UTC, anetteOlli commented on cypress/fixtures/example.json
> +{
skal fjerne den

2022-04-20 10:59 UTC, anetteOlli commented on pipeline.yml
> +      #      Triggers:
kjørte prettier på hele prosjektet

2022-04-20 12:23 UTC, pcb-unit commented on pipeline.yml
> +      #      Triggers:
jeg skjønte at det ikke var ny kode, alstå - men siden det dukket opp på lista over endringer tenkte jeg vi kunne rydde det bort om det ikke var i bruk.

2022-04-20 13:46 UTC, anetteOlli commented on pipeline.yml
> +      #      Triggers:
fikset

2022-04-20 13:46 UTC, anetteOlli commented on cypress/fixtures/example.json
> +{
fikset

2022-04-21 07:30 UTC, pcb-unit approved these changes

2022-04-21 10:14 UTC, merged